arviz 0.10.0 (Apache-2.0) has 1 incompatibilities in [tree_created]:
arviz 
  netcdf4 1.5.4 [arviz ()]
    numpy 1.19.2 [arviz (>=1.12)] [netcdf4 (>=1.9)] [pandas (>=1.15.4)] [scipy (>=1.14.5)] [matplotlib (>=1.15)] [cftime ()]
    cftime 1.2.1 (INCOMPATIBLE! HAS GPL-3.0-only) [netcdf4 ()]
  xarray 0.16.1 [arviz (>=0.16.1)]
  pandas 1.1.2 [arviz (>=0.23)]
    numpy 1.19.2 [arviz (>=1.12)] [netcdf4 (>=1.9)] [pandas (>=1.15.4)] [scipy (>=1.14.5)] [matplotlib (>=1.15)] [cftime ()]
    pytz 2020.1 [pandas (>=2017.2)]
    python-dateutil 2.8.1 [pandas (>=2.7.3)] [matplotlib (>=2.1)]
      six 1.15.0 [packaging ()] [python-dateutil (>=1.5)] [cycler ()]
  packaging 20.4 [arviz ()]
    six 1.15.0 [packaging ()] [python-dateutil (>=1.5)] [cycler ()]
    pyparsing 2.4.7 [packaging (>=2.0.2)] [matplotlib (!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3)]
  scipy 1.5.2 [arviz (>=0.19)]
    numpy 1.19.2 [arviz (>=1.12)] [netcdf4 (>=1.9)] [pandas (>=1.15.4)] [scipy (>=1.14.5)] [matplotlib (>=1.15)] [cftime ()]
  numpy 1.19.2 [arviz (>=1.12)] [netcdf4 (>=1.9)] [pandas (>=1.15.4)] [scipy (>=1.14.5)] [matplotlib (>=1.15)] [cftime ()]
  matplotlib 3.3.2 [arviz (>=3.0)]
    python-dateutil 2.8.1 [pandas (>=2.7.3)] [matplotlib (>=2.1)]
    pyparsing 2.4.7 [packaging (>=2.0.2)] [matplotlib (!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3)]
    pillow 7.2.0 [matplotlib (>=6.2.0)]
    kiwisolver 1.2.0 [matplotlib (>=1.0.1)]
    cycler 0.10.0 [matplotlib (>=0.10)]
  setuptools 50.3.0 [arviz (>=38.4)]
